"""Adversarial boundaries for agent-facing research operations."""

from __future__ import annotations

import shutil
from datetime import date
from pathlib import Path
from typing import Any

import pymupdf
import pytest
from pydantic import ValidationError as ModelValidationError

from research_kb.agent_api import ResearchAPI
from research_kb.config import Settings
from research_kb.exceptions import ValidationError
from research_kb.markdown_store import MarkdownStore
from research_kb.models import PaperNote, ReviewSubmission

ROOT = Path(__file__).parents[2]
ASSETS = ROOT / "src" / "research_kb" / "assets" / "vault"


class _LocalZotero:
    paths: dict[str, Path] = {}

    def __init__(self, *_args: object, **_kwargs: object) -> None:
        pass

    def __enter__(self) -> _LocalZotero:
        return self

    def __exit__(self, *_args: object) -> None:
        pass

    def resolve_attachment_path(self, attachment_key: str, **_kwargs: object) -> Path:
        return self.paths[attachment_key]


def _pdf(path: Path, pages: tuple[str, ...]) -> None:
    document = pymupdf.open()
    for text in pages:
        page = document.new_page()
        if text:
            page.insert_textbox((72, 72, 520, 760), text)
    document.save(path)
    document.close()


def _review_payload(session: dict[str, Any], scope: str) -> dict[str, object]:
    coverage = "complete" if scope == "full-text" else "partial"
    block = (
        "> **Generated by:** test\n> **Model:** test\n> **Date:** 2026-09-14\n"
        f"> **Scope:** {scope}\n> **Coverage:** {coverage}\n> **Human verified:** No\n\n"
        "### Summary\n\n- Synthetic result.\n\n### Main contribution\n\nSynthetic.\n\n"
        "### Main limitations\n\n- Synthetic evidence.\n\n### Reading recommendation\n\n"
        "**Read.** Synthetic.\n\n### Tags\n\n**Applied:** none\n**Suggested:** none"
    )
    return {
        "session_id": session["session_id"],
        "citekey": "pdf2026",
        "expected_revision": session["expected_revision"],
        "review_scope": scope,
        "review_coverage": coverage,
        "agent": "test",
        "model": "test",
        "review_date": "2026-09-14",
        "recommendation": "read",
        "recommendation_reason": "Synthetic.",
        "recommendation_confidence": "low",
        "managed_review": block,
    }


def _workspace(tmp_path: Path) -> tuple[Path, Settings, MarkdownStore]:
    workspace = tmp_path / "workspace"
    shutil.copytree(ASSETS, workspace / "vault")
    settings = Settings(_env_file=None, research_vault_path=workspace)  # type: ignore[call-arg]
    store = MarkdownStore(settings.papers_dir)
    store.create(
        PaperNote(
            zotero_key="BOUND001",
            citekey="boundary2026",
            title="Boundary Study",
            abstract="Synthetic abstract.",
        )
    )
    return workspace, settings, store


def test_project_identifier_cannot_traverse_workspace(tmp_path: Path) -> None:
    _workspace_root, settings, _store = _workspace(tmp_path)
    api = ResearchAPI(settings)

    with pytest.raises(ModelValidationError):
        api.call("projects", {"project_id": "../../outside"})
    with pytest.raises(ModelValidationError):
        api.call("projects", {"project_id": "/absolute"})
    with pytest.raises((ModelValidationError, ValidationError, ValueError)):
        api.call(
            "catalog-propose",
            {
                "request": {
                    "operation": "project-create",
                    "project_id": "../../outside",
                    "title": "Traversal",
                    "description": "Synthetic.",
                    "goals": ["Test boundaries."],
                    "scope_in": ["Synthetic data."],
                    "scope_out": ["Private data."],
                    "rationale": "Boundary test.",
                }
            },
        )


def test_extraction_cache_cannot_escape_through_symlinked_ancestor(tmp_path: Path) -> None:
    workspace, settings, _store = _workspace(tmp_path)
    outside = tmp_path / "outside-cache"
    outside.mkdir()
    settings.paper_text_dir.parent.mkdir(parents=True, exist_ok=True)
    settings.paper_text_dir.symlink_to(outside, target_is_directory=True)

    with pytest.raises(ValueError, match="symlink|outside"):
        ResearchAPI(settings).call("text", {"citekey": "boundary2026"})
    assert not tuple(outside.iterdir())
    assert workspace.is_dir()


def test_curation_proposal_state_cannot_escape_through_symlinked_ancestor(
    tmp_path: Path,
) -> None:
    _workspace_root, settings, store = _workspace(tmp_path)
    outside = tmp_path / "outside-state"
    outside.mkdir()
    settings.state_dir.mkdir()
    (settings.state_dir / "operations").symlink_to(outside, target_is_directory=True)

    with pytest.raises(ValidationError, match="symlink"):
        ResearchAPI(settings).call(
            "propose-curation",
            {
                "citekey": "boundary2026",
                "expected_revision": store.revision(store.note_path("boundary2026")),
                "items": [
                    {
                        "item_id": "tag-1",
                        "kind": "existing-tag",
                        "value": "domain/example",
                        "rationale": "Synthetic proposal.",
                    }
                ],
            },
        )
    assert not tuple(outside.rglob("*"))


def test_proposal_view_cannot_escape_through_symlinked_vault_directory(tmp_path: Path) -> None:
    _workspace_root, settings, store = _workspace(tmp_path)
    outside = tmp_path / "outside-view"
    outside.mkdir()
    proposals = settings.obsidian_vault_path / "System" / "Proposals"
    proposals.symlink_to(outside, target_is_directory=True)

    with pytest.raises(ValidationError, match="symlink"):
        ResearchAPI(settings).call(
            "propose-curation",
            {
                "citekey": "boundary2026",
                "expected_revision": store.revision(store.note_path("boundary2026")),
                "items": [
                    {
                        "item_id": "tag-1",
                        "kind": "existing-tag",
                        "value": "domain/example",
                        "rationale": "Synthetic proposal.",
                    }
                ],
            },
        )
    assert not tuple(outside.rglob("*"))


def test_verified_review_cannot_be_replaced_by_agent_submission(tmp_path: Path) -> None:
    _workspace_root, settings, store = _workspace(tmp_path)
    path = store.note_path("boundary2026")
    text = path.read_text(encoding="utf-8")
    path.write_text(
        text.replace("ai_review_human_verified: false", "ai_review_human_verified: true")
    )
    api = ResearchAPI(settings)
    context = api.call("context", {"citekey": "boundary2026", "scope": "abstract-only"})
    before = path.read_bytes()
    session = context["session"]
    block = (
        "> **Generated by:** test\n> **Model:** test\n> **Date:** 2026-09-14\n"
        "> **Scope:** abstract-only\n> **Coverage:** complete\n> **Human verified:** No\n\n"
        "### Summary\n\n- Synthetic.\n\n### Main contribution\n\nSynthetic.\n\n"
        "### Main limitations\n\n- Abstract only.\n\n### Reading recommendation\n\n"
        "**Read.** Synthetic.\n\n### Tags\n\n**Applied:** none\n**Suggested:** none"
    )
    submission = ReviewSubmission(
        session_id=session["session_id"],
        citekey="boundary2026",
        expected_revision=session["expected_revision"],
        review_scope="abstract-only",
        review_coverage="complete",
        agent="test",
        model="test",
        review_date=date(2026, 9, 14),
        recommendation="read",
        recommendation_reason="Synthetic.",
        recommendation_confidence="low",
        managed_review=block,
    )

    with pytest.raises(ValidationError, match="human-verified"):
        api.operations.submit_review(submission)
    assert path.read_bytes() == before


def test_artifact_full_text_source_requires_matching_extracted_evidence(tmp_path: Path) -> None:
    _workspace_root, settings, _store = _workspace(tmp_path)
    analyses = settings.obsidian_vault_path / "Literature" / "Analyses"
    before = set(analyses.glob("*.md"))

    with pytest.raises(ValidationError, match="matching extraction cache"):
        ResearchAPI(settings).call(
            "save-artifact",
            {
                "artifact_id": "unsupported-evidence",
                "title": "Unsupported evidence",
                "kind": "synthesis",
                "question": "What does full text establish?",
                "content": "A claim presented as full-text supported.",
                "sources": [
                    {
                        "citekey": "boundary2026",
                        "location": "page 9",
                        "evidence_scope": "full-text",
                    }
                ],
                "agent": "boundary-test",
            },
        )
    assert set(analyses.glob("*.md")) == before


def test_recovery_directory_symlink_is_rejected_before_history_access(tmp_path: Path) -> None:
    _workspace_root, settings, _store = _workspace(tmp_path)
    outside = tmp_path / "outside-recovery"
    outside.mkdir()
    settings.state_dir.mkdir()
    settings.recovery_dir.symlink_to(outside, target_is_directory=True)

    with pytest.raises(ValidationError, match="symlink|outside"):
        ResearchAPI(settings)
    assert not tuple(outside.iterdir())


def test_catalog_alias_state_cannot_escape_through_symlinked_ancestor(tmp_path: Path) -> None:
    _workspace_root, settings, _store = _workspace(tmp_path)
    settings.tag_registry_path.write_text(
        "# Tags\n\n### `domain/old`\n\nOld synthetic tag.\n", encoding="utf-8"
    )
    api = ResearchAPI(settings)
    outside = tmp_path / "outside-catalog"
    outside.mkdir()
    catalog_state = settings.state_dir / "catalog"
    catalog_state.symlink_to(outside, target_is_directory=True)

    with pytest.raises(ValidationError, match="outside|symlink"):
        api.call(
            "catalog-propose",
            {
                "request": {
                    "operation": "tag-rename",
                    "old_tag": "domain/old",
                    "new_tag": "domain/new",
                    "rationale": "Synthetic rename.",
                }
            },
        )
    assert not tuple(outside.rglob("*"))


@pytest.mark.parametrize(
    ("pages", "expected_scope"),
    [
        (("Full synthetic evidence. " * 50, "Second evidence page. " * 50), "full-text"),
        (("Partial synthetic evidence. " * 50, ""), "partial-text"),
    ],
)
def test_pdf_context_can_be_submitted_through_agent_api(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
    pages: tuple[str, ...],
    expected_scope: str,
) -> None:
    _workspace_root, settings, store = _workspace(tmp_path)
    original = store.note_path("boundary2026")
    original.unlink()
    store.create(
        PaperNote(
            zotero_key="PDFP0001",
            citekey="pdf2026",
            title="Synthetic PDF Study",
            abstract="Synthetic abstract.",
            pdf_attachment_key="PDFX0001",
        )
    )
    pdf = tmp_path / f"{expected_scope}.pdf"
    _pdf(pdf, pages)
    _LocalZotero.paths = {"PDFX0001": pdf}
    monkeypatch.setattr("research_kb.agent_api.ZoteroClient", _LocalZotero)

    api = ResearchAPI(settings)
    context = api.call("context", {"citekey": "pdf2026", "scope": "full-text"})
    assert context["scope"] == expected_scope

    receipt = api.call("submit-review", _review_payload(context["session"], expected_scope))

    note = store.parse(store.note_path("pdf2026")).note
    assert receipt["review_version"] == 1
    assert note.ai_review_status == "reviewed"
    assert note.ai_review_scope == expected_scope


def test_pdf_source_changed_after_context_refuses_api_submission(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _workspace_root, settings, store = _workspace(tmp_path)
    store.note_path("boundary2026").unlink()
    store.create(
        PaperNote(
            zotero_key="PDFP0001",
            citekey="pdf2026",
            title="Synthetic PDF Study",
            abstract="Synthetic abstract.",
            pdf_attachment_key="PDFX0001",
        )
    )
    pdf = tmp_path / "changing.pdf"
    _pdf(pdf, ("Original full evidence. " * 60,))
    _LocalZotero.paths = {"PDFX0001": pdf}
    monkeypatch.setattr("research_kb.agent_api.ZoteroClient", _LocalZotero)
    api = ResearchAPI(settings)
    context = api.call("context", {"citekey": "pdf2026", "scope": "full-text"})
    before = store.note_path("pdf2026").read_bytes()
    pdf.unlink()
    _pdf(pdf, ("Replacement evidence is materially different. " * 80,))

    with pytest.raises(ValidationError, match="inputs changed"):
        api.call("submit-review", _review_payload(context["session"], "full-text"))
    assert store.note_path("pdf2026").read_bytes() == before
