"""Validation of the required managed AI-review Markdown contract."""

from __future__ import annotations

import re
from dataclasses import dataclass

from research_kb.models import PaperNote

_HEADINGS = (
    "Summary",
    "Main contribution",
    "Main limitations",
    "Reading recommendation",
    "Tags",
)
_PROVENANCE = re.compile(
    r"(?m)^> \*\*(Generated by|Model|Date|Scope|Coverage|Human verified):\*\*[ \t]*(.*?)\s*$"
)


@dataclass(frozen=True)
class ContractViolation:
    """One structure or provenance violation inside a managed review block."""

    code: str
    message: str


def validate_managed_review(note: PaperNote, review_text: str) -> tuple[ContractViolation, ...]:
    """Return every deterministic review-format violation without modifying content."""
    violations: list[ContractViolation] = []
    for heading in _HEADINGS:
        if re.search(rf"(?m)^### {re.escape(heading)}[ \t]*$", review_text) is None:
            violations.append(
                ContractViolation(
                    "review-structure-invalid",
                    f"Managed AI review is missing the {heading!r} heading.",
                )
            )

    provenance_pairs = _PROVENANCE.findall(review_text)
    provenance = {label: value.strip() for label, value in provenance_pairs}
    provenance_labels = [label for label, _value in provenance_pairs]
    duplicates = sorted(
        {label for label in provenance_labels if provenance_labels.count(label) > 1}
    )
    for label in duplicates:
        violations.append(
            ContractViolation(
                "review-provenance-invalid",
                f"Managed AI review repeats provenance label {label!r}.",
            )
        )
    for label in ("Generated by", "Model", "Date", "Scope", "Coverage", "Human verified"):
        if not provenance.get(label):
            violations.append(
                ContractViolation(
                    "review-provenance-invalid",
                    f"Managed AI review is missing provenance label {label!r}.",
                )
            )

    expected = {
        "Generated by": note.ai_review_agent,
        "Date": note.ai_review_date.isoformat() if note.ai_review_date else None,
        "Scope": note.ai_review_scope,
        "Coverage": note.ai_review_coverage,
    }
    for label, value in expected.items():
        actual = provenance.get(label)
        if value is not None and actual is not None and not _equivalent(actual, str(value)):
            violations.append(
                ContractViolation(
                    "review-provenance-mismatch",
                    f"Managed review {label!r} does not match frontmatter.",
                )
            )
    model = provenance.get("Model")
    if note.ai_review_model and model and model != note.ai_review_model:
        violations.append(
            ContractViolation(
                "review-provenance-mismatch",
                "Managed review 'Model' does not match frontmatter.",
            )
        )
    verified = provenance.get("Human verified")
    if verified is not None and verified.casefold() != "no":
        violations.append(
            ContractViolation(
                "review-provenance-invalid",
                "Agent-generated review provenance must say 'Human verified: No'.",
            )
        )

    summary_bullets = re.findall(r"(?m)^-[ \t]+\S.*$", _section(review_text, "Summary"))
    if not 1 <= len(summary_bullets) <= 3:
        violations.append(
            ContractViolation(
                "review-structure-invalid",
                "Managed review Summary must contain one to three bullets.",
            )
        )
    if not _section(review_text, "Main contribution").strip():
        violations.append(
            ContractViolation(
                "review-structure-invalid",
                "Managed review Main contribution must not be empty.",
            )
        )
    limitation_bullets = re.findall(
        r"(?m)^-[ \t]+\S.*$", _section(review_text, "Main limitations")
    )
    if not 1 <= len(limitation_bullets) <= 2:
        violations.append(
            ContractViolation(
                "review-structure-invalid",
                "Managed review Main limitations must contain one or two bullets.",
            )
        )
    if not _section(review_text, "Reading recommendation").strip():
        violations.append(
            ContractViolation(
                "review-structure-invalid",
                "Managed review Reading recommendation must not be empty.",
            )
        )
    tags = _section(review_text, "Tags")
    for label in ("Applied", "Suggested"):
        if re.search(rf"(?m)^\*\*{label}:\*\*[ \t]*.*$", tags) is None:
            violations.append(
                ContractViolation(
                    "review-structure-invalid",
                    f"Managed review Tags section is missing {label!r}.",
                )
            )
    if re.search(r"(?m)^### Projects[ \t]*$", review_text) is not None:
        projects = _section(review_text, "Projects")
        for label in ("Relevant", "Considered"):
            if re.search(rf"(?m)^\*\*{label}:\*\*[ \t]*.*$", projects) is None:
                violations.append(
                    ContractViolation(
                        "review-structure-invalid",
                        f"Managed review Projects section is missing {label!r}.",
                    )
                )
    return tuple(violations)


def _section(review_text: str, heading: str) -> str:
    match = re.search(
        rf"(?ms)^### {re.escape(heading)}[ \t]*\n(?P<section>.*?)(?=^### |\Z)",
        review_text,
    )
    return match.group("section") if match else ""


def _equivalent(left: str, right: str) -> bool:
    normalized_left = re.sub(r"[-_\s]+", "-", left.strip().casefold())
    normalized_right = re.sub(r"[-_\s]+", "-", right.strip().casefold())
    return normalized_left == normalized_right
