"""Tests for read-only paper-note and review validation."""

from __future__ import annotations

from datetime import date
from pathlib import Path

import pytest
import yaml  # type: ignore[import-untyped]

from research_kb.config import Settings
from research_kb.exceptions import ValidationError
from research_kb.markdown_store import MarkdownStore
from research_kb.models import PaperNote
from research_kb.validation_service import (
    ValidationService,
    ValidationSeverity,
)


def _settings(tmp_path: Path, **updates: object) -> Settings:
    settings = Settings(_env_file=None, research_vault_path=tmp_path)
    if updates:
        settings = settings.model_copy(update=updates)
    return settings


def _registry(tmp_path: Path) -> None:
    path = tmp_path / "vault" / "System" / "tag-registry.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        "# Tag registry\n\n### `domain/weather`\n\nWeather research.\n\n"
        "### `method/diffusion-models`\n\nDiffusion-based models.\n",
        encoding="utf-8",
    )


def _store(tmp_path: Path) -> MarkdownStore:
    return MarkdownStore(tmp_path / "vault" / "Literature" / "Papers")


def _note(citekey: str = "doeUseful2026", **updates: object) -> PaperNote:
    note = PaperNote(
        zotero_key="ABCD1234",
        citekey=citekey,
        title="A useful paper",
    )
    return note.model_copy(update=updates)


def _reviewed_note(**updates: object) -> PaperNote:
    fields: dict[str, object] = {
        "pdf_attachment_key": "PDFX5678",
        "ai_review_status": "reviewed",
        "ai_review_scope": "full-text",
        "ai_review_coverage": "complete",
        "ai_review_agent": "Codex",
        "ai_review_date": date(2026, 8, 6),
        "ai_recommendation": "read",
        "ai_recommendation_reason": "Relevant methodology.",
        "ai_recommendation_confidence": "high",
        "tags": ("domain/weather",),
        "ai_applied_tags": ("method/diffusion-models",),
    }
    fields.update(updates)
    return _note(**fields)


def _add_review(store: MarkdownStore, path: Path) -> None:
    note = store.parse(path).note
    store.replace_managed_block(
        path,
        "AI_REVIEW",
        f"> **Generated by:** {note.ai_review_agent or 'Codex'}\n"
        f"> **Model:** {note.ai_review_model or 'not available'}\n"
        f"> **Date:** {note.ai_review_date or date(2026, 8, 6)}\n"
        f"> **Scope:** {note.ai_review_scope or 'full-text'}\n"
        f"> **Coverage:** {note.ai_review_coverage or 'complete'}\n"
        "> **Human verified:** No\n\n"
        "### Summary\n\n- Useful result.\n\n"
        "### Main contribution\n\nA reusable method.\n\n"
        "### Main limitations\n\n- Limited evaluation.\n\n"
        "### Reading recommendation\n\n**Read.** Relevant.\n\n"
        "### Tags\n\n"
        "**Applied:** `method/diffusion-models`\n"
        "**Suggested:** none",
    )


def _cache(tmp_path: Path, **updates: object) -> Path:
    metadata: dict[str, object] = {
        "citekey": "doeUseful2026",
        "zotero_key": "ABCD1234",
        "attachment_key": "PDFX5678",
        "source_mtime": 1.0,
        "source_size": 100,
        "extracted_at": "2026-08-06T12:00:00+00:00",
        "extractor": "pymupdf",
        "extractor_version": "1.26",
        "pages": 1,
        "failed_pages": [],
    }
    metadata.update(updates)
    path = tmp_path / ".research" / "paper-text" / "doeUseful2026.md"
    path.parent.mkdir(parents=True, exist_ok=True)
    frontmatter = yaml.safe_dump(metadata, sort_keys=False).rstrip()
    path.write_text(f"---\n{frontmatter}\n---\n\n<!-- PAGE 1 -->\n\nText.\n", encoding="utf-8")
    return path


def _codes(report: object) -> set[str]:
    return {issue.code for issue in report.issues}  # type: ignore[attr-defined]


def test_validates_default_and_complete_reviewed_notes(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.create(_note())
    reviewed = store.create(_reviewed_note().model_copy(update={"citekey": "reviewed2026"}))
    _add_review(store, reviewed)
    cache = _cache(tmp_path, citekey="reviewed2026")
    cache.rename(cache.with_name("reviewed2026.md"))

    report = ValidationService(_settings(tmp_path), store).run()

    assert report.ok
    assert report.checked_count == 2
    assert report.issues == report.errors == report.warnings == ()


def test_collects_review_tag_and_missing_cache_failures(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(
        _reviewed_note(
            ai_review_agent=" ",
            ai_recommendation_reason=None,
            tags=("domain/weather", "method/not-registered", "Bad Tag"),
            ai_applied_tags=(
                "domain/weather",
                "method/diffusion-models",
                "domain/weather",
                "method/diffusion-models",
                "domain/weather",
                "method/diffusion-models",
            ),
            ai_suggested_tags=("domain/weather", "data/new-one", "task/new-two"),
            zotero_tags=("domain/weather",),
        )
    )
    _add_review(store, path)

    report = ValidationService(_settings(tmp_path), store).run("doeUseful2026")

    assert not report.ok
    assert {
        "review-agent-missing",
        "review-field-missing",
        "tag-invalid",
        "tag-duplicate",
        "tag-unknown",
        "applied-tag-limit",
        "suggested-tag-limit",
        "suggested-tag-known",
        "suggested-tag-synchronized",
        "full-text-cache-missing",
    } <= _codes(report)


def test_unknown_approved_tag_can_be_a_warning(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.create(_note(tags=("domain/not-registered",)))

    report = ValidationService(
        _settings(tmp_path, unknown_tag_policy="warning"), store
    ).run()

    assert report.ok
    assert len(report.warnings) == 1
    assert report.warnings[0].severity is ValidationSeverity.WARNING
    assert report.warnings[0].code == "tag-unknown"


def test_tag_sync_status_requires_matching_tags_and_date(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.create(
        _note(
            tags=("domain/weather",),
            zotero_tags=(),
            zotero_tag_sync="synced",
            zotero_tag_sync_date=None,
        )
    )

    report = ValidationService(_settings(tmp_path), store).run()

    assert {"tag-sync-date-missing", "tag-sync-inconsistent"} <= _codes(report)


def test_unsynchronized_tag_state_rejects_stale_sync_date(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.create(_note(zotero_tag_sync="not-synced", zotero_tag_sync_date=date(2026, 8, 6)))

    report = ValidationService(_settings(tmp_path), store).run()

    assert "tag-sync-date-inconsistent" in _codes(report)


def test_reports_required_identity_enum_and_boolean_schema_failures(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(_note())
    contents = path.read_text(encoding="utf-8")
    contents = contents.replace("type: paper\n", "")
    contents = contents.replace("ai_review_status: not-reviewed", "ai_review_status: done")
    contents = contents.replace(
        "ai_review_human_verified: false", "ai_review_human_verified: 'no'"
    )
    path.write_text(contents, encoding="utf-8")

    report = ValidationService(_settings(tmp_path), store).run()

    assert "identity-missing" in _codes(report)
    assert "schema-invalid" in _codes(report)
    assert len(report.errors) >= 3


@pytest.mark.parametrize(
    "replacement",
    [
        "",
        "<!-- END MANAGED:AI_REVIEW -->\n<!-- END MANAGED:AI_REVIEW -->",
        "<!-- END MANAGED:ZOTERO_ANNOTATIONS -->",
    ],
)
def test_reports_missing_duplicate_and_overlapping_managed_markers(
    tmp_path: Path, replacement: str
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(_note())
    contents = path.read_text(encoding="utf-8")
    path.write_text(
        contents.replace("<!-- END MANAGED:AI_REVIEW -->", replacement),
        encoding="utf-8",
    )

    report = ValidationService(_settings(tmp_path), store).run()

    assert "managed-block-invalid" in _codes(report)


def test_full_text_cache_must_match_note_and_truthful_coverage(tmp_path: Path) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(_reviewed_note())
    _add_review(store, path)
    _cache(
        tmp_path,
        zotero_key="ZZZZ9999",
        attachment_key="OTHER123",
        failed_pages=[1],
    )

    report = ValidationService(_settings(tmp_path), store).run()

    assert sum(issue.code == "extraction-cache-mismatch" for issue in report.issues) == 2
    assert "review-coverage-inconsistent" in _codes(report)


def test_whole_vault_continues_after_malformed_note_and_target_errors_are_clear(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.create(_note("valid2026"))
    malformed = store.papers_dir / "broken.md"
    malformed.write_text("---\ntitle: [bad\n---\n", encoding="utf-8")
    before = malformed.read_bytes()
    service = ValidationService(_settings(tmp_path), store)

    report = service.run()
    missing = service.run("missing2026")

    assert report.checked_count == 2
    assert "frontmatter-invalid" in _codes(report)
    assert missing.checked_count == 0
    assert _codes(missing) == {"note-not-found"}
    assert malformed.read_bytes() == before
    with pytest.raises(ValidationError, match="unsafe citekey"):
        service.run("../escape")


def test_invalid_registry_is_reported_once_without_hiding_note_errors(tmp_path: Path) -> None:
    registry = tmp_path / "vault" / "System" / "tag-registry.md"
    registry.parent.mkdir(parents=True)
    registry.write_text("### `unknown/tag`\n\nDefinition.\n", encoding="utf-8")
    store = _store(tmp_path)
    path = store.create(_note())
    path.write_text(path.read_text().replace("title: A useful paper", "title: ''"))

    report = ValidationService(_settings(tmp_path), store).run()

    assert report.checked_count == 1
    assert "tag-registry-invalid" in _codes(report)
    assert "identity-missing" in _codes(report)


def test_queued_scope_without_review_evidence_does_not_require_a_cache(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    missing = ValidationService(_settings(tmp_path), store).run()

    assert missing.checked_count == 0
    assert _codes(missing) == {"papers-directory-missing"}

    store.create(
        _note(
            ai_review_status="queued",
            ai_review_scope="full-text",
            ai_review_coverage="unknown",
        )
    )
    queued = ValidationService(_settings(tmp_path), store).run()

    assert queued.ok
    assert "full-text-cache-missing" not in _codes(queued)


def test_symlinked_note_outside_the_vault_is_rejected_without_reading_it(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.papers_dir.mkdir(parents=True)
    outside = tmp_path / "private.md"
    outside.write_text("not a paper note", encoding="utf-8")
    linked = store.papers_dir / "linked.md"
    try:
        linked.symlink_to(outside)
    except OSError as error:  # pragma: no cover - platform permission boundary
        pytest.skip(f"symlinks unavailable: {error}")

    report = ValidationService(_settings(tmp_path), store).run()

    assert report.checked_count == 1
    assert _codes(report) == {"note-path-unsafe"}


def test_agent_workflow_baseline_detects_changes_to_every_human_owned_field(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    before = _note()
    path = store.create(before)
    service = ValidationService(_settings(tmp_path), store)
    snapshot_path = service.capture_workflow_snapshot("doeUseful2026")
    contents = path.read_text(encoding="utf-8")
    contents = contents.replace("human_read_status: unread", "human_read_status: read")
    contents = contents.replace("human_read_date: null", "human_read_date: '2026-08-06'")
    contents = contents.replace("human_rating: null", "human_rating: 5")
    contents = contents.replace("human_priority: null", "human_priority: 4")
    contents = contents.replace("human_relevance: null", "human_relevance: 3")
    contents = contents.replace("## Human notes\n", "## Human notes\nAgent changed this.\n")
    path.write_text(contents, encoding="utf-8")

    report = service.run("doeUseful2026")

    ownership = [issue for issue in report.issues if issue.code == "human-field-changed"]
    assert len(ownership) == 5
    assert any("must never infer" in issue.message for issue in ownership)
    assert "human-notes-changed" in _codes(report)
    assert snapshot_path.exists()


def test_successful_workflow_snapshot_can_be_consumed_without_touching_note(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    note_path = store.create(_note())
    original = note_path.read_bytes()
    service = ValidationService(_settings(tmp_path), store)
    snapshot = service.capture_workflow_snapshot("doeUseful2026")

    report = service.run("doeUseful2026")
    service.consume_workflow_snapshot("doeUseful2026")

    assert report.ok
    assert not snapshot.exists()
    assert note_path.read_bytes() == original


def test_reviewed_managed_block_requires_complete_structure_and_matching_provenance(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(_reviewed_note())
    store.replace_managed_block(
        path,
        "AI_REVIEW",
        "> **Generated by:** Other agent\n\n### Summary\n\nFour words, no bullets.",
    )
    _cache(tmp_path)

    report = ValidationService(_settings(tmp_path), store).run()

    assert {"review-structure-invalid", "review-provenance-invalid"} <= _codes(report)
    assert "review-provenance-mismatch" in _codes(report)


def test_non_review_status_cannot_hide_full_text_review_metadata_or_content(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(
        _note(
            ai_review_status="failed",
            ai_review_scope="full-text",
            ai_review_coverage="unknown",
            ai_review_agent="Codex",
            ai_recommendation="uncertain",
        )
    )
    store.replace_managed_block(path, "AI_REVIEW", "Review-like content despite failure.")

    report = ValidationService(_settings(tmp_path), store).run()

    assert {"review-status-inconsistent", "full-text-cache-missing"} <= _codes(report)


def test_non_utf8_note_and_cache_become_issues_without_aborting_the_vault(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    store.create(_note("valid2026"))
    (store.papers_dir / "bad.md").write_bytes(b"\xff\xfe")

    whole = ValidationService(_settings(tmp_path), store).run()

    assert whole.checked_count == 2
    assert "frontmatter-invalid" in _codes(whole)

    reviewed = store.create(_reviewed_note().model_copy(update={"citekey": "reviewed2026"}))
    _add_review(store, reviewed)
    cache = _cache(tmp_path, citekey="reviewed2026")
    cache = cache.rename(cache.with_name("reviewed2026.md"))
    cache.write_bytes(b"\xff\xfe")

    targeted = ValidationService(_settings(tmp_path), store).run("reviewed2026")

    assert "extraction-cache-invalid" in _codes(targeted)


def test_symlinked_roots_registry_and_cache_are_rejected(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    outside = tmp_path.parent / f"{tmp_path.name}-outside"
    outside.mkdir()
    outside_store = MarkdownStore(outside)
    outside_store.create(_note())
    papers = tmp_path / "vault" / "Literature" / "Papers"
    papers.parent.mkdir(parents=True, exist_ok=True)
    try:
        papers.symlink_to(outside, target_is_directory=True)
    except OSError as error:  # pragma: no cover - platform permission boundary
        pytest.skip(f"symlinks unavailable: {error}")

    unsafe_root = ValidationService(_settings(tmp_path), _store(tmp_path)).run()

    assert _codes(unsafe_root) == {"papers-directory-unsafe"}

    papers.unlink()
    store = _store(tmp_path)
    path = store.create(_reviewed_note())
    _add_review(store, path)
    registry = tmp_path / "vault" / "System" / "tag-registry.md"
    registry.unlink()
    external_registry = outside / "tag-registry.md"
    external_registry.write_text(
        "### `domain/weather`\n\nWeather.\n", encoding="utf-8"
    )
    registry.symlink_to(external_registry)
    cache = tmp_path / ".research" / "paper-text" / "doeUseful2026.md"
    cache.parent.mkdir(parents=True)
    cache.symlink_to(external_registry)

    unsafe_files = ValidationService(_settings(tmp_path), store).run()

    assert {"tag-registry-invalid", "extraction-cache-unsafe"} <= _codes(unsafe_files)


def test_extraction_cache_rejects_duplicate_fields_bad_pages_and_empty_text(
    tmp_path: Path,
) -> None:
    _registry(tmp_path)
    store = _store(tmp_path)
    path = store.create(_reviewed_note())
    _add_review(store, path)
    cache = _cache(tmp_path)
    contents = cache.read_text(encoding="utf-8")
    cache.write_text(
        contents.replace(
            "attachment_key: PDFX5678\n",
            "attachment_key: WRONG123\nattachment_key: PDFX5678\n",
        ),
        encoding="utf-8",
    )

    duplicate = ValidationService(_settings(tmp_path), store).run()

    assert "extraction-cache-invalid" in _codes(duplicate)

    _cache(tmp_path)
    contents = cache.read_text(encoding="utf-8")
    closing = contents.find("\n---\n", 4)
    cache.write_text(
        f"{contents[: closing + 5]}\n<!-- PAGE 2 -->\n",
        encoding="utf-8",
    )

    malformed_body = ValidationService(_settings(tmp_path), store).run()

    assert {"extraction-cache-pages-invalid", "extraction-cache-empty"} <= _codes(
        malformed_body
    )
