from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from research_kb.config import Settings
from research_kb.exceptions import ValidationError
from research_kb.extraction_service import ReviewContext
from research_kb.markdown_store import MarkdownStore
from research_kb.models import (
    ApprovedCurationRequest,
    CurationDecision,
    CurationItem,
    CurationProposalRequest,
    PaperNote,
    ReviewSubmission,
)
from research_kb.research_operations import CurationApprovalService, ResearchOperations


def _operations(tmp_path: Path) -> tuple[ResearchOperations, MarkdownStore]:
    settings = Settings(_env_file=None, research_vault_path=tmp_path)  # type: ignore[call-arg]
    settings.reading_profile_path.parent.mkdir(parents=True, exist_ok=True)
    settings.reading_profile_path.write_text("# Profile\n", encoding="utf-8")
    settings.tag_registry_path.write_text(
        "# Tags\n\n### `domain/weather`\n\nWeather research.\n", encoding="utf-8"
    )
    settings.projects_dir.mkdir(parents=True, exist_ok=True)
    store = MarkdownStore(settings.papers_dir)
    store.create(
        PaperNote(
            zotero_key="ABCD1234",
            citekey="doe2026",
            title="Weather",
            abstract="An abstract.",
        )
    )
    return ResearchOperations(settings, store), store


def _review(session_id: str, revision: str) -> ReviewSubmission:
    block = (
        "> **Generated by:** Codex\n> **Model:** test\n> **Date:** 2026-09-14\n"
        "> **Scope:** abstract-only\n> **Coverage:** complete\n"
        "> **Human verified:** No\n\n### Summary\n\n- A result.\n\n"
        "### Main contribution\n\nA contribution.\n\n### Main limitations\n\n"
        "- Abstract evidence only.\n\n### Reading recommendation\n\n"
        "**Read.** Relevant.\n\n### Tags\n\n"
        "**Applied:** `domain/weather`\n**Suggested:** none"
    )
    return ReviewSubmission(
        session_id=session_id,
        citekey="doe2026",
        expected_revision=revision,
        review_scope="abstract-only",
        review_coverage="complete",
        agent="Codex",
        model="test",
        review_date=date(2026, 9, 14),
        recommendation="read",
        recommendation_reason="Relevant.",
        recommendation_confidence="medium",
        applied_tags=("domain/weather",),
        managed_review=block,
    )


def test_abstract_review_is_one_validated_revision_checked_write(tmp_path: Path) -> None:
    operations, store = _operations(tmp_path)
    context, session = operations.start_review("doe2026", scope="auto")
    assert context.scope == "abstract-only"
    assert context.extracted_paper is None

    receipt = operations.submit_review(_review(session.session_id, session.expected_revision))
    note = store.parse(store.note_path("doe2026")).note
    assert note.ai_review_status == "reviewed"
    assert note.human_read_status == "unread"
    assert receipt.proposal_id
    assert receipt.revision == store.revision(store.note_path("doe2026"))
    assert not (operations._sessions / f"{session.session_id}.json").exists()
    assert (operations._history / f"review-{session.session_id}.json").is_file()

    status = operations.review_provenance_status("doe2026")
    assert status is not None
    assert not status.stale
    operations.settings.reading_profile_path.write_text("# Changed profile\n", encoding="utf-8")
    changed = operations.review_provenance_status("doe2026")
    assert changed is not None
    assert changed.stale
    assert changed.stale_reasons == ("reading-profile-changed",)


def test_review_provenance_status_is_none_without_review_history(tmp_path: Path) -> None:
    operations, _store = _operations(tmp_path)
    assert operations.review_provenance_status("doe2026") is None


def test_full_text_provenance_checks_only_local_cache_and_detects_cache_change(
    tmp_path: Path,
) -> None:
    operations, store = _operations(tmp_path)
    paper = store.note_path("doe2026")
    store.update_zotero_fields(paper, {"pdf_attachment_key": "PDFX5678"})
    cache = operations.settings.paper_text_dir / "doe2026.md"
    cache.parent.mkdir(parents=True, exist_ok=True)
    cache.write_text(
        "---\ncitekey: doe2026\nzotero_key: ABCD1234\nattachment_key: PDFX5678\n"
        "source_mtime: 1.0\nsource_size: 100\n"
        "extracted_at: 2026-09-14T12:00:00+00:00\nextractor: pymupdf\n"
        "extractor_version: test\npages: 1\nfailed_pages: []\n---\n\n"
        "<!-- PAGE 1 -->\n\nSynthetic full text.\n",
        encoding="utf-8",
    )

    class LocalContext:
        def review_context(self, citekey: str, *, scope: str) -> ReviewContext:
            assert citekey == "doe2026"
            return ReviewContext(
                paper_note=paper,
                extracted_paper=cache,
                reading_profile=operations.settings.reading_profile_path,
                tag_registry=operations.settings.tag_registry_path,
                scope="full-text",
            )

    full_operations = ResearchOperations(
        operations.settings,
        store,
        extraction=LocalContext(),  # type: ignore[arg-type]
    )
    _context, session = full_operations.start_review("doe2026", scope="full-text")
    submission = _review(session.session_id, session.expected_revision).model_copy(
        update={
            "review_scope": "full-text",
            "managed_review": _review(
                session.session_id, session.expected_revision
            ).managed_review.replace("Scope:** abstract-only", "Scope:** full-text"),
        }
    )
    full_operations.submit_review(submission)
    fresh = full_operations.review_provenance_status("doe2026")
    assert fresh is not None and not fresh.stale
    assert fresh.source_check == "local-cache"
    assert "Zotero PDF" in fresh.source_limitation

    cache.write_text(cache.read_text(encoding="utf-8") + "Changed cache.\n", encoding="utf-8")
    stale = full_operations.review_provenance_status("doe2026")
    assert stale is not None
    assert stale.stale_reasons == ("source-changed",)


def test_review_context_rejects_symlinked_paper_ancestor(tmp_path: Path) -> None:
    operations, _store = _operations(tmp_path)
    literature = operations.settings.obsidian_vault_path / "Literature"
    relocated = operations.settings.obsidian_vault_path / "RelocatedLiterature"
    literature.rename(relocated)
    literature.symlink_to(relocated, target_is_directory=True)

    with pytest.raises(ValidationError, match="symlink"):
        operations.get_context("doe2026", scope="abstract-only")


def test_review_rejects_concurrent_change_without_writing(tmp_path: Path) -> None:
    operations, store = _operations(tmp_path)
    _context, session = operations.start_review("doe2026")
    path = store.note_path("doe2026")
    store.update_zotero_fields(path, {"title": "Changed concurrently"})
    before = path.read_text(encoding="utf-8")

    with pytest.raises(ValidationError, match="inputs changed"):
        operations.submit_review(_review(session.session_id, session.expected_revision))
    assert path.read_text(encoding="utf-8") == before


def test_review_transaction_failure_restores_every_artifact(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    operations, store = _operations(tmp_path)
    _context, session = operations.start_review("doe2026")
    paper = store.note_path("doe2026")
    session_path = operations._sessions / f"{session.session_id}.json"
    before_paper = paper.read_bytes()
    before_session = session_path.read_bytes()
    import research_kb.operation_transaction as transaction_module

    real_commit = transaction_module._commit
    calls = 0

    def fail_second(path: Path, content: str | None, expected: str | None) -> None:
        nonlocal calls
        calls += 1
        if calls == 2:
            raise OSError("injected review write failure")
        real_commit(path, content, expected)

    monkeypatch.setattr(transaction_module, "_commit", fail_second)
    with pytest.raises(OSError, match="injected review write failure"):
        operations.submit_review(_review(session.session_id, session.expected_revision))

    assert paper.read_bytes() == before_paper
    assert session_path.read_bytes() == before_session
    assert not tuple(operations._proposals.glob("*.json"))
    assert not tuple((operations.settings.obsidian_vault_path / "System/Proposals").glob("*.md"))
    assert not tuple(operations._history.glob("review-*.json"))


def test_approval_requires_an_explicit_decision_for_every_item(tmp_path: Path) -> None:
    operations, store = _operations(tmp_path)
    _context, session = operations.start_review("doe2026")
    receipt = operations.submit_review(_review(session.session_id, session.expected_revision))
    assert receipt.proposal_id is not None
    approval = CurationApprovalService(operations)

    with pytest.raises(ValidationError, match="every proposal item"):
        approval.apply(
            ApprovedCurationRequest(
                proposal_id=receipt.proposal_id,
                decisions=(),
                expected_revision=receipt.revision,
            )
        )

    result = approval.apply(
        ApprovedCurationRequest(
            proposal_id=receipt.proposal_id,
            decisions=(CurationDecision(item_id="tag-existing-1", decision="accepted"),),
            expected_revision=receipt.revision,
        )
    )
    assert store.parse(store.note_path("doe2026")).note.tags == ("domain/weather",)
    assert result.kind == "curation-approval"


def test_project_approval_stages_and_updates_both_derived_blocks(tmp_path: Path) -> None:
    operations, store = _operations(tmp_path)
    project = operations.settings.projects_dir / "weather-project.md"
    project.write_text(
        "---\nschema_version: 1\ntype: project\nproject_id: weather-project\n"
        "title: Weather project\nstatus: active\nstarted:\ntarget:\ntags: []\n---\n\n"
        "# Weather project\n\n## Description\n\nSynthetic.\n\n## Related papers\n\n"
        "<!-- BEGIN MANAGED:PROJECT_PAPERS -->\n\nNo papers are linked to this project.\n\n"
        "<!-- END MANAGED:PROJECT_PAPERS -->\n\n## Notes\n",
        encoding="utf-8",
    )
    snapshot = operations.validator.capture_workflow_snapshot("doe2026")
    revision = store.revision(store.note_path("doe2026"))
    proposal = operations.propose_curation(
        CurationProposalRequest(
            citekey="doe2026",
            expected_revision=revision,
            items=(
                CurationItem(
                    item_id="project-1",
                    kind="project-link",
                    value="weather-project",
                    rationale="Matches the project scope.",
                ),
            ),
        )
    )
    approval = CurationApprovalService(operations)
    request = ApprovedCurationRequest(
        proposal_id=proposal.proposal_id,
        decisions=(CurationDecision(item_id="project-1", decision="accepted"),),
        expected_revision=revision,
    )
    preview = approval.preview(request)
    assert {item.path for item in preview} >= {
        "vault/Literature/Papers/doe2026.md",
        "vault/Projects/weather-project.md",
    }
    receipt = approval.apply(request)
    assert not snapshot.exists()
    assert "[[weather-project]]" in store.note_path("doe2026").read_text(encoding="utf-8")
    assert "[[doe2026]]" in project.read_text(encoding="utf-8")
    approval.undo(receipt.operation_id, receipt.revisions)
    assert snapshot.exists()
    assert "[[weather-project]]" not in store.note_path("doe2026").read_text(encoding="utf-8")
    assert "[[doe2026]]" not in project.read_text(encoding="utf-8")
    proposal_path = operations._proposals / f"{proposal.proposal_id}.json"
    assert json.loads(proposal_path.read_text(encoding="utf-8"))["status"] == "pending"


def test_review_persists_project_goal_rationale_in_proposal(tmp_path: Path) -> None:
    operations, _store = _operations(tmp_path)
    project = operations.settings.projects_dir / "weather-project.md"
    project.write_text(
        "---\nschema_version: 1\ntype: project\nproject_id: weather-project\n"
        "title: Weather project\nstatus: active\nstarted:\ntarget:\ntags: []\n---\n\n"
        "# Weather project\n\n## Description\n\nSynthetic.\n\n## Related papers\n\n"
        "<!-- BEGIN MANAGED:PROJECT_PAPERS -->\n\nNo papers are linked to this project.\n\n"
        "<!-- END MANAGED:PROJECT_PAPERS -->\n\n## Notes\n",
        encoding="utf-8",
    )
    _context, session = operations.start_review("doe2026")
    base = _review(session.session_id, session.expected_revision)
    rationale = "Directly evaluates the project's forecast-transfer goal."
    submission = base.model_copy(
        update={
            "suggested_projects": ("weather-project",),
            "suggested_project_rationales": {"weather-project": rationale},
            "managed_review": base.managed_review
            + "\n\n### Projects\n\n**Relevant:** `weather-project`\n**Considered:** none",
        }
    )
    receipt = operations.submit_review(submission)
    assert receipt.proposal_id is not None
    proposal = operations._load_proposal(receipt.proposal_id)
    project_item = next(item for item in proposal.items if item.kind == "project-link")
    assert project_item.rationale == rationale


def test_unknown_project_approval_fails_before_any_vault_change(tmp_path: Path) -> None:
    operations, store = _operations(tmp_path)
    paper = store.note_path("doe2026")
    revision = store.revision(paper)
    proposal = operations.propose_curation(
        CurationProposalRequest(
            citekey="doe2026",
            expected_revision=revision,
            items=(
                CurationItem(
                    item_id="project-1",
                    kind="project-link",
                    value="missing-project",
                    rationale="Synthetic invalid proposal.",
                ),
            ),
        )
    )
    before = {
        path: path.read_bytes()
        for path in operations.settings.obsidian_vault_path.rglob("*")
        if path.is_file()
    }
    with pytest.raises(ValidationError, match="unknown"):
        CurationApprovalService(operations).apply(
            ApprovedCurationRequest(
                proposal_id=proposal.proposal_id,
                decisions=(CurationDecision(item_id="project-1", decision="accepted"),),
                expected_revision=revision,
            )
        )
    assert all(path.read_bytes() == content for path, content in before.items())


def test_edit_during_staging_causes_conflict_and_preserves_external_edit(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    operations, store = _operations(tmp_path)
    project = operations.settings.projects_dir / "weather-project.md"
    project.write_text(
        "---\nschema_version: 1\ntype: project\nproject_id: weather-project\n"
        "title: Weather\nstatus: active\nstarted:\ntarget:\ntags: []\n---\n\n"
        "# Weather\n\n## Description\n\nSynthetic.\n\n## Related papers\n\n"
        "<!-- BEGIN MANAGED:PROJECT_PAPERS -->\n\nNo papers are linked to this project.\n\n"
        "<!-- END MANAGED:PROJECT_PAPERS -->\n\n## Notes\n",
        encoding="utf-8",
    )
    paper = store.note_path("doe2026")
    revision = store.revision(paper)
    proposal = operations.propose_curation(
        CurationProposalRequest(
            citekey="doe2026",
            expected_revision=revision,
            items=(
                CurationItem(
                    item_id="project-1",
                    kind="project-link",
                    value="weather-project",
                    rationale="Synthetic.",
                ),
            ),
        )
    )
    from research_kb.project_service import ProjectService

    real_index = ProjectService.index

    def editing_index(service: ProjectService, *, dry_run: bool = False) -> object:
        paper.write_text(paper.read_text(encoding="utf-8") + "\nExternal edit.\n", encoding="utf-8")
        return real_index(service, dry_run=dry_run)

    monkeypatch.setattr(ProjectService, "index", editing_index)
    with pytest.raises(ValidationError, match="revision conflict"):
        CurationApprovalService(operations).apply(
            ApprovedCurationRequest(
                proposal_id=proposal.proposal_id,
                decisions=(CurationDecision(item_id="project-1", decision="accepted"),),
                expected_revision=revision,
            )
        )
    assert paper.read_text(encoding="utf-8").endswith("External edit.\n")
    assert "[[doe2026]]" not in project.read_text(encoding="utf-8")


def test_all_rejected_decisions_atomically_resolve_proposal_state(tmp_path: Path) -> None:
    operations, store = _operations(tmp_path)
    revision = store.revision(store.note_path("doe2026"))
    proposal = operations.propose_curation(
        CurationProposalRequest(
            citekey="doe2026",
            expected_revision=revision,
            items=(
                CurationItem(
                    item_id="existing-1",
                    kind="existing-tag",
                    value="domain/weather",
                    rationale="Synthetic.",
                ),
            ),
        )
    )
    receipt = CurationApprovalService(operations).apply(
        ApprovedCurationRequest(
            proposal_id=proposal.proposal_id,
            decisions=(CurationDecision(item_id="existing-1", decision="rejected"),),
            expected_revision=revision,
        )
    )
    proposal_path = operations._proposals / f"{proposal.proposal_id}.json"
    state = json.loads(proposal_path.read_text(encoding="utf-8"))
    assert state["status"] == "applied"
    assert state["decisions"] == [{"decision": "rejected", "item_id": "existing-1"}]
    assert ".research/operations/curation-proposals" in " ".join(receipt.affected_paths)
