from pathlib import Path

import yaml  # type: ignore[import-untyped]

from research_kb.models import PaperNote

ROOT = Path(__file__).parents[2]
AGENT_FILES = (ROOT / "AGENTS.md", ROOT / "CLAUDE.md")
SKILL = ROOT / ".claude" / "skills" / "paper-review" / "SKILL.md"
CODEX_SKILL = ROOT / ".codex" / "skills" / "paper-review"
TEMPLATE = ROOT / "vault" / "System" / "Templates" / "Paper.md"


def _frontmatter(text: str) -> dict[str, object]:
    _, raw, _ = text.split("---", maxsplit=2)
    parsed = yaml.safe_load(raw)
    assert isinstance(parsed, dict)
    return parsed


def test_agent_instructions_are_equivalent_and_route_to_the_skill() -> None:
    instructions = tuple(path.read_text(encoding="utf-8") for path in AGENT_FILES)

    assert instructions[0] == instructions[1]
    contract = instructions[0]
    assert "not expected to be on the shell's `PATH`" in contract
    assert "do not probe for or invoke a bare `research` executable first" in contract
    assert ".venv/bin/research ..." in contract
    assert "`paper-review` skill" in contract


def test_both_agents_resolve_to_one_source() -> None:
    for path in (AGENT_FILES[0], CODEX_SKILL):
        assert path.is_symlink(), f"{path} must stay a symlink so the copies cannot drift"

    assert AGENT_FILES[0].resolve() == AGENT_FILES[1].resolve()
    assert CODEX_SKILL.resolve() == SKILL.parent.resolve()
    assert (CODEX_SKILL / "SKILL.md").read_text(encoding="utf-8") == SKILL.read_text(
        encoding="utf-8"
    )


def test_skill_carries_an_executable_review_workflow() -> None:
    skill = SKILL.read_text(encoding="utf-8")

    assert skill.index("uv run research review-context <citekey>") < skill.index(
        "uv run research validate <citekey>"
    )
    for required_input in (
        "paper note",
        "extracted paper text",
        "vault/System/reading-profile.md",
        "vault/System/tag-registry.md",
    ):
        assert required_input in skill

    for provenance_label in (
        "**Generated by:**",
        "**Model:**",
        "**Date:**",
        "**Scope:**",
        "**Coverage:**",
        "**Human verified:** No",
    ):
        assert provenance_label in skill
    for review_heading in (
        "### Summary",
        "### Main contribution",
        "### Main limitations",
        "### Reading recommendation",
        "### Tags",
    ):
        assert review_heading in skill
    assert "**Applied:**" in skill
    assert "**Suggested:**" in skill


def test_agent_contract_protects_human_state_and_limits_reviews() -> None:
    contract = AGENT_FILES[0].read_text(encoding="utf-8")
    skill = SKILL.read_text(encoding="utf-8")

    for protected_field in (
        "human_read_status",
        "human_read_date",
        "human_rating",
        "human_priority",
        "human_relevance",
    ):
        assert protected_field in contract
    for protection in (
        "Never promote tags into `tags`",
        "Never repair validation failures by changing protected content",
    ):
        assert protection in contract

    for invariant in (
        "120–180",
        "below 200",
        "at most three summary bullets",
        "one or two important limitations",
        "at most five existing registry tags",
        "at most two genuinely new proposals",
        "ai_review_human_verified: false",
        "Never invent page references",
    ):
        assert invariant in skill


def test_paper_template_has_current_schema_defaults_and_managed_blocks() -> None:
    text = TEMPLATE.read_text(encoding="utf-8")
    metadata = _frontmatter(text)

    assert set(metadata) == set(PaperNote.model_fields)
    PaperNote.model_validate(metadata)
    assert metadata["schema_version"] == 1
    assert metadata["type"] == "paper"
    assert metadata["human_read_status"] == "unread"
    assert metadata["ai_review_status"] == "not-reviewed"
    assert metadata["ai_review_version"] == 0
    assert metadata["ai_review_human_verified"] is False
    assert metadata["tags"] == []
    assert metadata["ai_applied_tags"] == []
    assert metadata["ai_suggested_tags"] == []
    assert metadata["zotero_missing"] is False

    for block in ("AI_REVIEW", "ZOTERO_ANNOTATIONS"):
        begin = f"<!-- BEGIN MANAGED:{block} -->"
        end = f"<!-- END MANAGED:{block} -->"
        assert text.count(begin) == 1
        assert text.count(end) == 1
        assert text.index(begin) < text.index(end)
    assert "No AI review has been generated." in text
    assert "No Zotero annotations have been imported." in text


def test_paper_template_keeps_human_and_ai_sections_separate() -> None:
    text = TEMPLATE.read_text(encoding="utf-8")

    human_start = text.index("## Human notes")
    ai_start = text.index("## AI review")
    human_section = text[human_start:ai_start]
    assert "MANAGED:" not in human_section
    for heading in ("### Summary", "### Important results", "### Critique", "### Connections"):
        assert heading in human_section
