"""Catalog lifecycle operations against synthetic workspaces."""

from datetime import date
from pathlib import Path

import pytest
import yaml  # type: ignore[import-untyped]
from pydantic import ValidationError as PydanticValidationError

from research_kb.catalog_operations import (
    CatalogApprovalService,
    CatalogOperations,
    ProjectArchiveRequest,
    ProjectCreateRequest,
    ProjectUpdateRequest,
    TagMergeRequest,
    TagRenameRequest,
    resolve_tag_alias,
)
from research_kb.config import Settings
from research_kb.exceptions import ValidationError
from research_kb.markdown_store import MarkdownStore
from research_kb.models import PaperNote
from research_kb.project_registry import parse_project_note
from research_kb.search_service import SearchRequest, SearchService
from research_kb.tag_registry import parse_tag_registry
from research_kb.validation_service import ValidationService

REGISTRY = """# Tag registry

## Domain

### `domain/weather`

Weather systems.

### `domain/climate`

Climate systems.

## Method

### `method/forecasting`

Forecasting methods.
"""


def _operations(tmp_path: Path) -> tuple[CatalogOperations, CatalogApprovalService, MarkdownStore]:
    (tmp_path / "vault/System").mkdir(parents=True)
    (tmp_path / "vault/Projects").mkdir(parents=True)
    (tmp_path / "vault/Literature/Papers").mkdir(parents=True)
    (tmp_path / "vault/System/tag-registry.md").write_text(REGISTRY, encoding="utf-8")
    settings = Settings(_env_file=None, research_vault_path=tmp_path)
    store = MarkdownStore(settings.papers_dir)
    operations = CatalogOperations(settings, store)
    return operations, CatalogApprovalService(operations), store


def _create_request(project_id: str = "weather-models") -> ProjectCreateRequest:
    return ProjectCreateRequest(
        project_id=project_id,
        title="Weather models",
        description="Study weather models.",
        goals=("Compare methods",),
        scope_in=("Forecasts",),
        scope_out=("Operations",),
        tags=("domain/weather",),
        rationale="User requested a project for this question.",
    )


def _make_full_text_review(store: MarkdownStore, path: Path, workspace: Path) -> None:
    store.update_ai_fields(
        path,
        {
            "ai_review_status": "reviewed",
            "ai_review_scope": "full-text",
            "ai_review_coverage": "complete",
            "ai_review_agent": "Codex",
            "ai_review_date": date(2026, 8, 6),
            "ai_recommendation": "read",
            "ai_recommendation_reason": "Relevant.",
            "ai_recommendation_confidence": "high",
            "ai_applied_tags": ("domain/weather",),
        },
    )
    store.replace_managed_block(
        path,
        "AI_REVIEW",
        "> **Generated by:** Codex\n> **Model:** test\n> **Date:** 2026-08-06\n"
        "> **Scope:** full-text\n> **Coverage:** complete\n> **Human verified:** No\n\n"
        "### Summary\n\n- Useful.\n\n### Main contribution\n\nA method.\n\n"
        "### Main limitations\n\n- Limited.\n\n### Reading recommendation\n\n"
        "**Read.** Relevant.\n\n### Tags\n\n**Applied:** `domain/weather`\n"
        "**Suggested:** none",
    )
    metadata = {
        "citekey": "doe2026",
        "zotero_key": "ABCD1234",
        "attachment_key": "PDFX5678",
        "source_mtime": 1.0,
        "source_size": 100,
        "extracted_at": "2026-08-06T12:00:00+00:00",
        "extractor": "pymupdf",
        "extractor_version": "1.26",
        "pages": 1,
        "failed_pages": [],
    }
    cache = workspace / ".research/paper-text/doe2026.md"
    cache.parent.mkdir(parents=True)
    header = yaml.safe_dump(metadata, sort_keys=False).rstrip()
    cache.write_text(f"---\n{header}\n---\n\n<!-- PAGE 1 -->\n\nText.\n", encoding="utf-8")


def test_project_create_is_proposal_only_until_trusted_apply(tmp_path: Path) -> None:
    operations, approval, _store = _operations(tmp_path)
    path = tmp_path / "vault/Projects/weather-models.md"

    proposal = operations.propose(_create_request())

    assert not path.exists()
    mirror = tmp_path / f"vault/System/Proposals/{proposal.proposal_id}.md"
    assert "status: pending" in mirror.read_text(encoding="utf-8")
    preview = operations.preview(proposal.proposal_id)
    assert preview.operation == "project-create"
    assert preview.files[0].path == "vault/Projects/weather-models.md"
    receipt = approval.apply(proposal.proposal_id)
    assert receipt.files[0].before_revision is None
    assert parse_project_note(path).tags == ("domain/weather",)
    assert "status: applied" in mirror.read_text(encoding="utf-8")


def test_project_update_and_archive_preserve_links_and_notes(tmp_path: Path) -> None:
    operations, approval, store = _operations(tmp_path)
    created = operations.propose(_create_request())
    approval.apply(created.proposal_id)
    path = tmp_path / "vault/Projects/weather-models.md"
    store.create(
        PaperNote(
            zotero_key="ABCD1234",
            citekey="doe2026",
            title="Linked paper",
            projects=("weather-models",),
        )
    )
    text = path.read_text(encoding="utf-8").replace("## Notes\n", "## Notes\n\nHuman text.\n")
    path.write_text(text, encoding="utf-8")

    updated = operations.propose(
        ProjectUpdateRequest(
            project_id="weather-models",
            title="Weather foundation models",
            goals=("Evaluate transfer",),
            rationale="The user expanded the project.",
            reassessment="Existing links remain in scope.",
        )
    )
    approval.apply(updated.proposal_id)
    archived = operations.propose(
        ProjectArchiveRequest(
            project_id="weather-models",
            rationale="The user closed the project.",
            reassessment="Keep all paper links as historical context.",
        )
    )
    approval.apply(archived.proposal_id)

    final = path.read_text(encoding="utf-8")
    assert "# Weather foundation models" in final
    assert "- [[doe2026]]" in final
    assert "Human text." in final
    assert parse_project_note(path).status == "archived"


def test_tag_rename_updates_curated_tags_but_preserves_review_history(tmp_path: Path) -> None:
    operations, approval, store = _operations(tmp_path)
    paper = store.create(
        PaperNote(
            zotero_key="ABCD1234",
            citekey="doe2026",
            title="Weather paper",
            pdf_attachment_key="PDFX5678",
            tags=("domain/weather",),
        )
    )
    _make_full_text_review(store, paper, tmp_path)
    validator = ValidationService(operations.settings, store)
    snapshot = validator.capture_workflow_snapshot("doe2026")

    proposal = operations.propose(
        TagRenameRequest(
            old_tag="domain/weather",
            new_tag="domain/weather-prediction",
            rationale="Use the more precise approved name.",
        )
    )
    assert store.parse(paper).note.tags == ("domain/weather",)
    approval.apply(proposal.proposal_id)

    note = store.parse(paper).note
    assert note.tags == ("domain/weather-prediction",)
    assert note.ai_applied_tags == ("domain/weather",)
    assert note.zotero_tag_sync == "not-synced"
    registry = parse_tag_registry(tmp_path / "vault/System/tag-registry.md")
    assert {"domain/weather", "domain/weather-prediction"} <= set(registry.names)
    aliases = tmp_path / ".research/catalog/tag-aliases.json"
    assert '"domain/weather": "domain/weather-prediction"' in aliases.read_text()
    assert resolve_tag_alias(operations.settings, "domain/weather") == "domain/weather-prediction"
    results = SearchService(operations.settings).search(SearchRequest(tags=("domain/weather",)))
    assert [hit.citekey for hit in results.hits] == ["doe2026"]
    assert not snapshot.exists()
    assert validator.run("doe2026").ok


def test_tag_merge_deduplicates_curated_tags(tmp_path: Path) -> None:
    operations, approval, store = _operations(tmp_path)
    paper = store.create(
        PaperNote(
            zotero_key="ABCD1234",
            citekey="doe2026",
            title="Climate paper",
            tags=("domain/weather", "domain/climate"),
        )
    )

    proposal = operations.propose(
        TagMergeRequest(
            source_tags=("domain/weather",),
            target_tag="domain/climate",
            rationale="The user approved consolidating these concepts.",
        )
    )
    approval.apply(proposal.proposal_id)

    assert store.parse(paper).note.tags == ("domain/climate",)


def test_stale_project_proposal_is_rejected_without_writing(tmp_path: Path) -> None:
    operations, approval, _store = _operations(tmp_path)
    created = operations.propose(_create_request())
    approval.apply(created.proposal_id)
    proposal = operations.propose(
        ProjectUpdateRequest(
            project_id="weather-models",
            description="New description.",
            rationale="Requested edit.",
        )
    )
    path = tmp_path / "vault/Projects/weather-models.md"
    path.write_text(path.read_text(encoding="utf-8") + "\nConcurrent note.\n", encoding="utf-8")
    before = path.read_text(encoding="utf-8")

    with pytest.raises(ValidationError, match="stale|revision conflict"):
        approval.apply(proposal.proposal_id)

    assert path.read_text(encoding="utf-8") == before


def test_project_request_rejects_path_traversal_before_file_access() -> None:
    with pytest.raises(PydanticValidationError, match="lowercase kebab-case"):
        ProjectArchiveRequest(
            project_id="../../outside",
            rationale="Archive request.",
            reassessment="Preserve links.",
        )


def test_catalog_state_rejects_symlinked_ancestor(tmp_path: Path) -> None:
    outside = tmp_path / "outside"
    outside.mkdir()
    (tmp_path / ".research").symlink_to(outside, target_is_directory=True)
    settings = Settings(_env_file=None, research_vault_path=tmp_path)

    with pytest.raises(ValidationError, match="symlinked catalog path"):
        CatalogOperations(settings)


def test_reject_persists_status_and_clears_pending_mirror(tmp_path: Path) -> None:
    operations, approval, _store = _operations(tmp_path)
    proposal = operations.propose(_create_request())

    approval.reject(proposal.proposal_id)

    assert operations._load(proposal.proposal_id).status == "rejected"
    mirror = tmp_path / f"vault/System/Proposals/{proposal.proposal_id}.md"
    text = mirror.read_text(encoding="utf-8")
    assert "status: rejected" in text
    assert "pending_count: 0" in text
    with pytest.raises(ValidationError, match="already rejected"):
        approval.apply(proposal.proposal_id)


def test_custom_obsidian_directory_stages_project_index_safely(tmp_path: Path) -> None:
    notes = tmp_path / "notes"
    (notes / "System").mkdir(parents=True)
    (notes / "Projects").mkdir(parents=True)
    (notes / "Literature/Papers").mkdir(parents=True)
    (notes / "System/tag-registry.md").write_text(REGISTRY, encoding="utf-8")
    settings = Settings(
        _env_file=None,
        research_vault_path=tmp_path,
        research_obsidian_dir="notes",
    )
    operations = CatalogOperations(settings)
    approval = CatalogApprovalService(operations)

    proposal = operations.propose(_create_request("custom-layout"))
    approval.apply(proposal.proposal_id)

    assert (notes / "Projects/custom-layout.md").is_file()
