from datetime import date

import pytest

from research_kb.models import PaperNote
from research_kb.review_contract import validate_managed_review


def _note() -> PaperNote:
    return PaperNote(
        zotero_key="FORMAT01",
        citekey="format2026",
        title="Review format",
        ai_review_scope="abstract-only",
        ai_review_coverage="complete",
        ai_review_agent="test-agent",
        ai_review_model="test-model",
        ai_review_date=date(2026, 9, 14),
    )


def _review(existing_label: str, new_label: str) -> str:
    return f"""> **Generated by:** test-agent
> **Model:** test-model
> **Date:** 2026-09-14
> **Scope:** abstract-only
> **Coverage:** complete
> **Human verified:** No

### Summary

- A bounded summary.

### Main contribution

A contribution supported by the abstract.

### Main limitations

- Only abstract evidence was available.

### Reading recommendation

**Read.** Relevant to the synthetic profile.

### Tags

**{existing_label}:** `domain/example`
**{new_label}:** none"""


@pytest.mark.parametrize(
    ("existing_label", "new_label"),
    [
        ("Suggested existing tags", "Suggested new tags"),
        ("Applied", "Suggested"),
    ],
)
def test_review_contract_accepts_clear_and_legacy_tag_labels(
    existing_label: str, new_label: str
) -> None:
    assert validate_managed_review(_note(), _review(existing_label, new_label)) == ()


def test_review_contract_reports_a_missing_new_tag_category() -> None:
    review = _review("Suggested existing tags", "Suggested new tags").replace(
        "**Suggested new tags:** none", ""
    )

    violations = validate_managed_review(_note(), review)

    assert any("Suggested new tags" in violation.message for violation in violations)
